# Generated by Django 2.2.16 on 2022-08-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_userforregistarions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userforregistarions',
            old_name='confirm_code',
            new_name='confirmation_code',
        ),
    ]
