# Generated by Django 2.2.16 on 2022-08-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220829_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['year']},
        ),
    ]
