# Generated by Django 2.2.16 on 2022-08-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220822_1312'),
        ('reviews', '0004_category_genre_title'),
    ]

    operations = [
    ]
